# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetupTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('prerequisite', models.TextField(blank=True, max_length=300, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepname', models.CharField(blank=True, max_length=100, null=True)),
                ('stepdesc', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='setuptemplate',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Steps'),
        ),
    ]
