# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20170808_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setuptemplate',
            options={'ordering': ('productName',)},
        ),
        migrations.AlterModelOptions(
            name='steps',
            options={'ordering': ('stepNum',)},
        ),
        migrations.RenameField(
            model_name='setuptemplate',
            old_name='timestamp',
            new_name='creationTime',
        ),
        migrations.RenameField(
            model_name='setuptemplate',
            old_name='prerequisite',
            new_name='minimumRequirement',
        ),
        migrations.RenameField(
            model_name='setuptemplate',
            old_name='edition',
            new_name='platformType',
        ),
        migrations.RenameField(
            model_name='setuptemplate',
            old_name='subcategory',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='setuptemplate',
            old_name='type',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='steps',
            old_name='stepdesc',
            new_name='stepDesc',
        ),
        migrations.RenameField(
            model_name='steps',
            old_name='stepname',
            new_name='stepTitle',
        ),
        migrations.AddField(
            model_name='setuptemplate',
            name='approxTotalTimeReqd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setuptemplate',
            name='numOfUpdates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setuptemplate',
            name='numOfViews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setuptemplate',
            name='refImage',
            field=models.ImageField(default=None, upload_to=b''),
        ),
        migrations.AddField(
            model_name='steps',
            name='image',
            field=models.ImageField(default=None, upload_to=b''),
        ),
        migrations.AddField(
            model_name='steps',
            name='stepNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='steps',
            name='stepTimeReqd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='steps',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
