# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20170808_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steps',
            old_name='image',
            new_name='stepImage',
        ),
    ]
