# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20170808_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setuptemplate',
            name='refImage',
            field=models.ImageField(default=None, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='steps',
            name='stepImage',
            field=models.ImageField(default=None, null=True, upload_to=b''),
        ),
    ]
