# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20170809_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuptemplate',
            name='downloadLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setuptemplate',
            name='expertiseLevel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setuptemplate',
            name='githubRepo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setuptemplate',
            name='officialSite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setuptemplate',
            name='precautions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setuptemplate',
            name='stackoverflow',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setuptemplate',
            name='wikipage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setuptemplate',
            name='youtubeChannel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='steps',
            name='codeSnip',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='setuptemplate',
            name='refImage',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='steps',
            name='stepImage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
